function Animacao() {
  return (
    <main className="main-logo">
      <section className="container">
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-terciaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-quinaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-15 cor-quartenaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-5 cor-quinaria"></div>
          <div className="celula size-5 cor-terciaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-13 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-9 cor-quinaria"></div>
          <div className="celula size-9 cor-quartenaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-7 cor-terciaria"></div>
          <div className="celula size-11 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-15 cor-quinaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-13 cor-quartenaria"></div>
          <div className="celula size-5 cor-terciaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-9 cor-secundaria"></div>
          <div className="celula size-9 cor-quinaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-15 cor-terciaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-quartenaria"></div>
          <div className="celula size-7 cor-quinaria"></div>
          <div className="celula size-7 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-5 cor-terciaria"></div>
          <div className="celula size-5 cor-quinaria"></div>
          <div className="celula size-7 cor-quartenaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-5 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-7 cor-terciaria"></div>
          <div className="celula size-7 cor-quinaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-quartenaria"></div>
          <div className="celula size-15 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-5 cor-terciaria"></div>
          <div className="celula size-13 cor-quinaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-19 cor-quartenaria"></div>
          <div className="celula size-7 cor-secundaria"></div>
          <div className="celula size-11 cor-quinaria"></div>
          <div className="celula size-19 cor-terciaria"></div>
          <div className="celula size-3 cor-quartenaria"></div>
          <div className="celula size-9 cor-quinaria"></div>
          <div className="celula size-7 cor-secundaria"></div>
          <div className="celula size-11 cor-terciaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-terciaria"></div>
          <div className="celula size-7 cor-quartenaria"></div>
          <div className="celula size-5 cor-secundaria"></div>
          <div className="celula size-17 cor-quinaria"></div>
          <div className="celula size-13 cor-secundaria"></div>
          <div className="celula size-19 cor-terciaria"></div>
          <div className="celula size-3 cor-quartenaria"></div>
          <div className="celula size-5 cor-quinaria"></div>
          <div className="celula size-7 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-secundaria"></div>
          <div className="celula size-19 cor-quartenaria"></div>
          <div className="celula size-19 cor-terciaria"></div>
          <div className="celula size-7 cor-secundaria"></div>
          <div className="celula size-13 cor-terciaria"></div>
          <div className="celula size-9 cor-quinaria"></div>
          <div className="celula size-3 cor-quartenaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-3 cor-quinaria"></div>
          <div className="celula size-13 cor-terciaria"></div>
          <div className="celula size-19 cor-quinaria"></div>
          <div className="celula size-17 cor-secundaria"></div>
          <div className="celula size-7 cor-quartenaria"></div>
          <div className="celula size-3 cor-terciaria"></div>
          <div className="celula size-5 cor-secundaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-19 cor-quinaria"></div>
          <div className="celula size-5 cor-quartenaria"></div>
          <div className="celula size-11 cor-secundaria"></div>
          <div className="celula size-3 cor-quinaria"></div>
          <div className="celula size-17 cor-quartenaria"></div>
          <div className="celula size-9 cor-terciaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula size-7 cor-quartenaria"></div>
          <div className="celula size-15 cor-terciaria"></div>
          <div className="celula size-3 cor-quinaria"></div>
          <div className="celula size-5 cor-terciaria"></div>
          <div className="celula size-17 cor-secundaria"></div>
          <div className="celula size-3 cor-quartenaria"></div>
          <div className="celula size-7 cor-quinaria"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
          <div className="celula"></div>
        </div>
        <div className="linha">
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
          <div className="celula transparencia1"></div>
        </div>
        <div className="linha">
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
          <div className="celula transparencia"></div>
        </div>
      </section>
    </main>
  );
}

export default Animacao;
